disabled: false
chest-name: "%playername%'s Death Chest"
information-message-general: "&aYou died.. Get to your chest! Quick! Before someone else gets it!"
information-message-location: "&aCoordinates for your chest: x: &c%x% &ay: &c%y% &az: &c%z%"
